; NL2Bot ESP32 Firmware — Dual Node Architecture
[platformio]
default_envs = hull_node, turret_node

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo@^3.0.5
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1

[env:hull_node]
board = esp32cam
build_src_filter = +<hull_node/>
build_flags =
    -DHULL_NODE
    -DBOARD_HAS_PSRAM
lib_deps =
    ${env.lib_deps}
    rfetick/MPU6050_light@^1.2.1

[env:turret_node]
board = esp32cam
build_src_filter = +<turret_node/>
build_flags =
    -DTURRET_NODE
    -DBOARD_HAS_PSRAM
lib_deps =
    ${env.lib_deps}
    pololu/VL53L0X@^1.3.1

[env:train_node]
board = esp32cam
build_src_filter = +<train_node/>
build_flags =
    -DTRAIN_NODE
    -DBOARD_HAS_PSRAM
