steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/robot4kid/planning-server:latest'
      - '-f'
      - 'planning_server/Dockerfile'
      - '.'
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/robot4kid/planning-server:latest'
timeout: 600s
